[build]
  publish = "."
  functions = "netlify/functions"

 #Optional: local dev proxy for functions
 [[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
